CIRCUMSTANCE_CHOICES = (
    (1, "in fermata / in sosta"),
    (2, "ripartiva dopo una sosta / apriva una portiera"),
    (3, "stava parcheggiando"),
    (4, "usciva da un parcheggio, da un luogo privato, da una strada vicinale"),
    (5, "entrava in un parcheggio, in un luogo privato, in una strada vicinale"),
    (6, "si immetteva in una piazza a senso rotatorio"),
    (7, "circolava su una piazza a senso rotatorio"),
    (8, "tamponava procedendo nello stesso senso e nella stessa fila"),
    (9, "procedeva nello stesso senso, ma in una fila diversa"),
    (10, "cambiava fila"),
    (11, "sorpassava"),
    (12, "girava a destra"),
    (13, "girava a sinistra"),
    (14, "retrocedeva"),
    (15, "invadeva la sede stradale riservata alla circolazione in senso inverso"),
    (16, "proveniva da destra"),
    (17, "non aveva osservato il segnale di precedenza o di semaforo rosso"),
)
